### ISSUE TITLE
Transition from romulus to Jekyll

### ISSUE THREAD

**Issue by rmehner** [nodecopter/nodecopter.com#20]
Hey there,

this site now runs with [Jekyll](http://jekyllrb.com) and a super basic gh-pages setup. Yay. I've made a backup of the old romulus version to the [romulus branch](https://github.com/nodecopter/nodecopter.com/tree/romulus).

Everything still seems to work and pages a build instantly without needing a separate build / deploy step. Should make the workflow even easier for contributions now.

Few things of note:
- I've deleted the master branch, as we don't need it anymore and to avoid confusion
- default branch of this repo is `gh-pages` now

Think that's all. Tell me if you find some glitches or even better: go fix them ;)

Greetings,
- Robin

**Comment by felixge** [comment]
:heart: you da man!
