### ISSUE TITLE
AR.Drone Parrot 1.0 Support

### ISSUE THREAD

**Issue by AgtLucas** [nodecopter/nodecopter.com#42]
Hello guys,

Can you confirm that a Parrot 1.0 will work with Nodecopter?

I read this on site...

> The AR Drone 1.0 may also be supported by some libraries, but most of the community uses 2.0 drones.

...but, just to have more information about support.

Thanks!

**Comment by rmehner** [comment]
We don't test it on the 1.0. Some things work AFAIK, but certainly not all.

As we never got our hands on a 1.0 we can't tell for sure. Safest bet is getting a 2.0.

**Comment by AgtLucas** [comment]
Well, seems like I'll have to buy a 2.0 version :smile:

Thanks @rmehner !
